Update for d3v6
mojoaxel/d3-sunburst pull request #8
Opened 2020-10-10 13:39 UTC by puripant

I edited the code as necessary to work with d3v6. This should satisfy #7

2020-10-10 20:06 UTC, mojoaxel requested changes
Amazing! :tada: 
Thank you very much! Can I please ask you for the following changes so I can merge this:

- update d3 in the package.json to the up-to-date version
- update the examples to work with the new d3 version. (`d3/d3.min.js` --> `d3/dist/d3.min.js`)

2020-10-11 04:07 UTC, puripant commented
I have updated as requested. Let me know if there's anything else.

2020-10-11 10:20 UTC, mojoaxel approved these changes

2020-10-11 10:22 UTC, merged

2020-10-11 10:22 UTC, mojoaxel commented
@puripant Thank you very much for your help!